sudo: false

language: node_js
node_js:
  - 12

branches:
  only:
    - master
deploy:
  skip_cleanup: true
  provider: heroku
  app: trevis-heroku-test
  api_key:
    secure: 0e4f7d59-adb2-4a33-bd44-1172c423c39c